//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class hfrEntities : DbContext
    {
        public hfrEntities()
            : base("name=hfrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Faaliyet> tbl_Faaliyet { get; set; }
        public virtual DbSet<tbl_YetkiGrup> tbl_YetkiGrup { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
    
        public virtual int SP_FaaliyetDurumGuncelleme(Nullable<int> yil, Nullable<int> ay, Nullable<int> hafta, Nullable<int> kullaniciID, Nullable<int> deger)
        {
            var yilParameter = yil.HasValue ?
                new ObjectParameter("yil", yil) :
                new ObjectParameter("yil", typeof(int));
    
            var ayParameter = ay.HasValue ?
                new ObjectParameter("ay", ay) :
                new ObjectParameter("ay", typeof(int));
    
            var haftaParameter = hafta.HasValue ?
                new ObjectParameter("hafta", hafta) :
                new ObjectParameter("hafta", typeof(int));
    
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("kullaniciID", kullaniciID) :
                new ObjectParameter("kullaniciID", typeof(int));
    
            var degerParameter = deger.HasValue ?
                new ObjectParameter("deger", deger) :
                new ObjectParameter("deger", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_FaaliyetDurumGuncelleme", yilParameter, ayParameter, haftaParameter, kullaniciIDParameter, degerParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_FaaliyetKontrol(Nullable<int> id, Nullable<System.DateTime> tarih, Nullable<int> hafta, string baslik, string faaliyet)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            var haftaParameter = hafta.HasValue ?
                new ObjectParameter("hafta", hafta) :
                new ObjectParameter("hafta", typeof(int));
    
            var baslikParameter = baslik != null ?
                new ObjectParameter("baslik", baslik) :
                new ObjectParameter("baslik", typeof(string));
    
            var faaliyetParameter = faaliyet != null ?
                new ObjectParameter("faaliyet", faaliyet) :
                new ObjectParameter("faaliyet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_FaaliyetKontrol", idParameter, tarihParameter, haftaParameter, baslikParameter, faaliyetParameter);
        }
    
        public virtual ObjectResult<SP_KullaniciDetay_Result> SP_KullaniciDetay(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KullaniciDetay_Result>("SP_KullaniciDetay", idParameter);
        }
    
        public virtual ObjectResult<SP_KullaniciFaaliyetListele_Result> SP_KullaniciFaaliyetListele(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KullaniciFaaliyetListele_Result>("SP_KullaniciFaaliyetListele", iDParameter);
        }
    
        public virtual ObjectResult<SP_KullaniciYetki_Result> SP_KullaniciYetki()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KullaniciYetki_Result>("SP_KullaniciYetki");
        }
    
        public virtual ObjectResult<SP_FaaliyetArama_Result> SP_FaaliyetArama(Nullable<System.DateTime> tarih, Nullable<int> hafta, Nullable<int> id)
        {
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            var haftaParameter = hafta.HasValue ?
                new ObjectParameter("hafta", hafta) :
                new ObjectParameter("hafta", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FaaliyetArama_Result>("SP_FaaliyetArama", tarihParameter, haftaParameter, idParameter);
        }
    
        public virtual int SP_FaaliyetGuncelle(Nullable<int> id, Nullable<int> kullaniciID, Nullable<System.DateTime> tarih, Nullable<int> hafta, string baslik, string faaliyet)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("kullaniciID", kullaniciID) :
                new ObjectParameter("kullaniciID", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            var haftaParameter = hafta.HasValue ?
                new ObjectParameter("hafta", hafta) :
                new ObjectParameter("hafta", typeof(int));
    
            var baslikParameter = baslik != null ?
                new ObjectParameter("baslik", baslik) :
                new ObjectParameter("baslik", typeof(string));
    
            var faaliyetParameter = faaliyet != null ?
                new ObjectParameter("faaliyet", faaliyet) :
                new ObjectParameter("faaliyet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_FaaliyetGuncelle", idParameter, kullaniciIDParameter, tarihParameter, haftaParameter, baslikParameter, faaliyetParameter);
        }
    }
}
