name: mia_hfr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.6+3 # Login Bilgisi Tutmak için Kullandım.

  modal_progress_hud: ^0.1.3
  curved_navigation_bar: ^0.3.2 #navigation bar için kullandım.
  progress_dialog: ^1.2.0 #login de giriş yaparken api ye bağlanısıya kadar, progress dialog için kullandm

  flutter:
    sdk: flutter
  http: ^0.12.2
  icon_picker: "^1.0.0" # Datetime işlemleri  
  flutter_localizations: # Türkce çevirmek için kullandım.
    sdk: flutter

  path_provider: ^1.6.5 #Provider için kullandım verileri dinamik bir şekilde yapmak için
  pedantic: ^1.9.0  
  dotted_border: ^2.0.0
  sqflite: ^2.0.0+3 #Veritabanı için kullandım
  flutter_datetime_picker: # Tarih için kullandım, yeni sürümde sorun olduğu için githubdan paket çekildi
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  flutter_local_notifications: ^3.0.1+6 # Bildirimler için notificationu kullandım
  timezone: ^0.5.6
  encrypt: ^5.0.0 #şiftelemek için kullandığım bir paket

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
cupertino_icons: ^0.1.3

 
      
     

dev_dependencies:

  flutter_test:
    sdk: flutter
 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo-Mia.png
    - images/AnaBack.png
    - images/add_alarm.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
